### ISSUE TITLE
AIC in BTm with explanatory variables

### ISSUE THREAD

**Issue by kauedesousa** [hturner/BradleyTerry2#9]
Dear @hturner , 

I am trying to get AIC (and deviance) from a BTm with explanatory variables, but I didn't get any result. There is any special way to compute it, or it is not implemented for BTm with explanatory variables?

Here an example using the flatlizards data 

```R
library(BradleyTerry2)

data("flatlizards")

mod <- BTm(1, winner, loser, ~ SVL[..] + (1|..), data = flatlizards)

newdata  <- list(contests = data.frame(
  winner = factor(c("lizard048", "lizard060"),
                  levels = c("lizard006", "lizard011",
                             "lizard048", "lizard060")),
  loser = factor(c("lizard006", "lizard011"),
                 levels = c("lizard006", "lizard011",
                            "lizard048", "lizard060"))
),
predictors = flatlizards$predictors[c(3, 6, 27, 33), ])

predict(mod)
predict(mod, newdata = newdata)

AIC(mod)
AIC(mod, newdata = newdata)
```

**Comment by hturner** [comment]
No, it is not implemented. When you have a random effect the model becomes a GLMM and is fit using penalized quasi-likelihood. In this case, the likelihood and related statistics (deviance, AIC)  are not defined. Perhaps some quasi-AIC could be defined, but this would require some consideration, as the algorithm alternates between fitting the random effect variance and fitting the fixed effects.

There are other GLMM implementations in R, but I don't see one that allows us to specify the design matrices for the fixed and random effects. This is essential for the Bradley-Terry model as we need to specify differences between the random effects for each player. So for the moment, we are limited to `glmmPQL()`. (There may be another way to pass the correct specification to an alternative GLMM function, but that would require more work).

This means that for inference you are limited to the Z tests in the model summary.

**Comment by DavidFirth** [comment]
Just quickly to agree with Heather's answer, and to add: Together with research collaborators I am currently exploring possibilities other than glmmPQL, to implement as the back-end for structured Bradley-Terry models.  But that's not something that will appear very soon in BradleyTerry2: it's likely to take some time.

**Comment by kauedesousa** [comment]
Thank you @hturner and @DavidFirth for your quick response. Best wishes on the development of these new tools.
